"""empty message

Revision ID: 3572fe074529
Revises: e83aba60f515
Create Date: 2025-10-16 14:05:27.983664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3572fe074529'
down_revision = 'e83aba60f515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_sobrantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_captura', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_captura', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['id_usuario_captura'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_sobrantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_captura')
        batch_op.drop_column('id_usuario_captura')

    # ### end Alembic commands ###
