"""Añade Acta de hechos al enum de DocumentoBaja

Revision ID: 37559b990408
Revises: 7822c2ac1100
Create Date: 2025-10-14 12:52:34.507419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37559b990408'
down_revision = '7822c2ac1100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', mysql.ENUM('Solicitud de Baja', 'Dictamen Técnico', 'Denuncia de Robo', 'Acta de Siniestro', 'Avalúo Comercial', 'Acta de Comité', 'Acta de Baja', 'Otro'), nullable=False))

    # ### end Alembic commands ###
