"""Añade 'Solicitud de Baja' al enum de DocumentoBaja

Revision ID: 5719efc3e81c
Revises: 17554422ead4
Create Date: 2025-10-11 10:15:05.416207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5719efc3e81c'
down_revision = '17554422ead4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_baja', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['id_usuario_captura'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_baja', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
