"""Añade Acta de hechos al enum de DocumentoBaja

Revision ID: 6fa16478fb32
Revises: a214ae5e42c6
Create Date: 2025-10-14 12:50:25.941287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa16478fb32'
down_revision = 'a214ae5e42c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_columna', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.drop_column('test_columna')

    # ### end Alembic commands ###
