"""Añade Acta de hechos al enum de DocumentoBaja

Revision ID: 7822c2ac1100
Revises: 6fa16478fb32
Create Date: 2025-10-14 12:51:26.231674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7822c2ac1100'
down_revision = '6fa16478fb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.drop_column('test_columna')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_columna', mysql.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
