"""Añadimos  tipo de resguardo inventario

Revision ID: 7aafa1095ce9
Revises: f24fabf3d541
Create Date: 2025-10-20 13:43:31.488395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aafa1095ce9'
down_revision = 'f24fabf3d541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_resguardo_inventariado', sa.Integer(), server_default='0', nullable=False, comment='Filtra los bienes a inventariar. 0=Resguardo, 1=Sujeto a Control.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventarios', schema=None) as batch_op:
        batch_op.drop_column('tipo_resguardo_inventariado')

    # ### end Alembic commands ###
