"""Añade Acta de hechos al enum de DocumentoBaja

Revision ID: 9334e5c42ed7
Revises: 37559b990408
Create Date: 2025-10-14 12:52:56.666024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9334e5c42ed7'
down_revision = '37559b990408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.Enum('Solicitud de Baja', 'Dictamen Técnico', 'Denuncia de Robo', 'Acta de Siniestro', 'Avalúo Comercial', 'Acta de Comité', 'Acta de Baja', 'Acta de Investigación', 'Fotografías del bien', 'Acta de echos', 'Otro', name='tipo_doc_baja_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###
