"""Elimina columnas redundantes nombre_archivo y ruta_archivo de DocumentoBaja

Revision ID: a214ae5e42c6
Revises: 5719efc3e81c
Create Date: 2025-10-11 10:31:11.618736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a214ae5e42c6'
down_revision = '5719efc3e81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.drop_column('ruta_archivo')
        batch_op.drop_column('nombre_archivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_baja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_archivo', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('ruta_archivo', mysql.VARCHAR(length=512), nullable=False))

    # ### end Alembic commands ###
