"""Migración inicial de la base de datos

Revision ID: b42e8770e30b
Revises: 
Create Date: 2025-10-18 09:51:05.616944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42e8770e30b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombres', sa.String(length=255), nullable=True, comment='Nombre completo del usuario'))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True, comment='Número de teléfono de contacto'))
        batch_op.create_unique_constraint(None, ['telefono'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombres')

    # ### end Alembic commands ###
