"""Agregamos modelos de modulo de inventarios

Revision ID: e83aba60f515
Revises: 9334e5c42ed7
Create Date: 2025-10-15 09:49:05.471460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83aba60f515'
down_revision = '9334e5c42ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False, comment="Nombre descriptivo del inventario, ej: 'Inventario Anual 2025'"),
    sa.Column('tipo', sa.Enum('Físico-Contable', 'Preventivo', name='tipo_inventario_enum'), nullable=False, comment='Distingue entre un inventario formal completo y una revisión rápida o preventiva.'),
    sa.Column('estatus', sa.Enum('Planificado', 'En Progreso', 'En Conciliación', 'Finalizado', 'Cancelado', name='estatus_inventario_enum'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True, comment="Se establece cuando el estatus cambia a 'Finalizado'."),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_areas',
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios.id'], ),
    sa.PrimaryKeyConstraint('inventario_id', 'area_id')
    )
    op.create_table('inventario_brigadas',
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('inventario_id', 'user_id')
    )
    op.create_table('inventario_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('id_resguardo_esperado', sa.Integer(), nullable=True, comment='FK a Resguardo al iniciar el inventario.'),
    sa.Column('id_area_esperada', sa.Integer(), nullable=True, comment='FK a Area donde se esperaba encontrar el bien.'),
    sa.Column('nombre_resguardante_esperado', sa.String(length=255), nullable=True, comment='Nombre del resguardante esperado.'),
    sa.Column('estatus_hallazgo', sa.Enum('Pendiente', 'Localizado', 'No Localizado', 'Localizado con Discrepancia', name='estatus_hallazgo_enum'), nullable=False),
    sa.Column('condicion_fisica_reportada', sa.String(length=50), nullable=True, comment='Estado del bien observado en campo (Bueno, Regular, Malo).'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id_usuario_verificador', sa.Integer(), nullable=True, comment='Miembro de la brigada que verificó el bien.'),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_bien'], ['bienes.id'], ),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_verificador'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_sobrantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('id_area_encontrado', sa.Integer(), nullable=False, comment='Área donde fue físicamente localizado.'),
    sa.Column('descripcion_bien', sa.Text(), nullable=False, comment='Descripción detallada de lo que se encontró.'),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('condicion_fisica', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estatus_resolucion', sa.Enum('Pendiente de Identificación', 'Identificado y Reubicado', 'Requiere Alta', 'Alta Completada', name='estatus_resolucion_sobrante_enum'), nullable=False),
    sa.Column('id_bien_asociado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area_encontrado'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['id_bien_asociado'], ['bienes.id'], ),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_inventario_detalle', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=512), nullable=False, comment='Ruta donde se guarda el archivo de la imagen.'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Nota o descripción sobre lo que muestra la foto.'),
    sa.Column('fecha_carga', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_inventario_detalle'], ['inventario_detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_sobrante_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_inventario_sobrante', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=512), nullable=False, comment='Ruta donde se guarda el archivo de la imagen.'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Nota sobre lo que muestra la foto.'),
    sa.Column('fecha_carga', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_inventario_sobrante'], ['inventario_sobrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario_sobrante_fotos')
    op.drop_table('inventario_fotos')
    op.drop_table('inventario_sobrantes')
    op.drop_table('inventario_detalle')
    op.drop_table('inventario_brigadas')
    op.drop_table('inventario_areas')
    op.drop_table('inventarios')
    # ### end Alembic commands ###
