"""Add applicant fields to OficiosTraspaso

Revision ID: f24fabf3d541
Revises: b42e8770e30b
Create Date: 2025-10-20 11:11:05.213944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24fabf3d541'
down_revision = 'b42e8770e30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficios_traspaso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nombre_Solicitante', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_area_solicitante', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Jefe_Area_Solicitante', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'areas', ['id_area_solicitante'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficios_traspaso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Jefe_Area_Solicitante')
        batch_op.drop_column('id_area_solicitante')
        batch_op.drop_column('Nombre_Solicitante')

    # ### end Alembic commands ###
